//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ERPContext : DbContext
    {
        public ERPContext()
            : base("name=ERPContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<instorage> instorages { get; set; }
        public virtual DbSet<material> materials { get; set; }
        public virtual DbSet<outstorage> outstorages { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<provider> providers { get; set; }
        public virtual DbSet<pur_indent> pur_indent { get; set; }
        public virtual DbSet<pur_MRB> pur_MRB { get; set; }
        public virtual DbSet<pur_quality> pur_quality { get; set; }
        public virtual DbSet<pur_quotation> pur_quotation { get; set; }
        public virtual DbSet<sale_indent> sale_indent { get; set; }
        public virtual DbSet<sale_quotation> sale_quotation { get; set; }
        public virtual DbSet<section> sections { get; set; }
        public virtual DbSet<staff> staffs { get; set; }
        public virtual DbSet<station> stations { get; set; }
        public virtual DbSet<warehouse> warehouses { get; set; }
    }
}
