//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class instorage
    {
        public int i_id { get; set; }
        public Nullable<int> i_material { get; set; }
        public Nullable<int> i_num { get; set; }
        public Nullable<double> i_volume { get; set; }
        public Nullable<double> i_weight { get; set; }
        public Nullable<int> i_staff { get; set; }
        public Nullable<int> i_warehouse { get; set; }
    
        public virtual material material { get; set; }
        public virtual staff staff { get; set; }
        public virtual warehouse warehouse { get; set; }
    }
}
