//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class material
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public material()
        {
            this.instorages = new HashSet<instorage>();
            this.outstorages = new HashSet<outstorage>();
            this.pur_indent = new HashSet<pur_indent>();
            this.pur_MRB = new HashSet<pur_MRB>();
            this.pur_quality = new HashSet<pur_quality>();
            this.pur_quotation = new HashSet<pur_quotation>();
        }
    
        public int m_id { get; set; }
        public string m_name { get; set; }
        public string m_unit { get; set; }
        public double m_price { get; set; }
        public int m_num { get; set; }
        public Nullable<int> m_warehouse { get; set; }
        public Nullable<int> m_provider { get; set; }
        public string m_note { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<instorage> instorages { get; set; }
        public virtual provider provider { get; set; }
        public virtual warehouse warehouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<outstorage> outstorages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pur_indent> pur_indent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pur_MRB> pur_MRB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pur_quality> pur_quality { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pur_quotation> pur_quotation { get; set; }
    }
}
