//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class pur_quotation
    {
        public int q_id { get; set; }
        public Nullable<int> q_name { get; set; }
        public Nullable<System.DateTime> q_time { get; set; }
        public Nullable<int> q_material { get; set; }
        public Nullable<int> q_num { get; set; }
        public Nullable<int> q_auditor { get; set; }
        public Nullable<System.DateTime> q_auditdate { get; set; }
        public Nullable<int> q_auditstate { get; set; }
        public string q_note { get; set; }
    
        public virtual material material { get; set; }
        public virtual staff staff { get; set; }
        public virtual staff staff1 { get; set; }
    }
}
