//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class pur_quality
    {
        public int q_id { get; set; }
        public Nullable<int> q_provider { get; set; }
        public Nullable<int> q_material { get; set; }
        public Nullable<int> q_num { get; set; }
        public Nullable<int> q_staff { get; set; }
        public string q_information { get; set; }
        public Nullable<int> q_state { get; set; }
        public Nullable<System.DateTime> q_date { get; set; }
    
        public virtual material material { get; set; }
        public virtual provider provider { get; set; }
        public virtual staff staff { get; set; }
    }
}
