//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class pur_indent
    {
        public int p_id { get; set; }
        public Nullable<int> p_staff { get; set; }
        public Nullable<System.DateTime> p_indentdate { get; set; }
        public Nullable<System.DateTime> p_pickdate { get; set; }
        public Nullable<int> p_material { get; set; }
        public Nullable<int> p_num { get; set; }
        public Nullable<int> p_indentstate { get; set; }
        public string p_logistics { get; set; }
        public Nullable<int> p_logisticeid { get; set; }
        public string p_note { get; set; }
    
        public virtual material material { get; set; }
        public virtual staff staff { get; set; }
    }
}
