//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sale_indent
    {
        public int s_id { get; set; }
        public Nullable<int> s_staff { get; set; }
        public Nullable<int> s_product { get; set; }
        public Nullable<int> s_num { get; set; }
        public Nullable<int> s_customer { get; set; }
        public Nullable<double> s_price { get; set; }
        public Nullable<System.DateTime> s_date { get; set; }
        public Nullable<int> s_state { get; set; }
        public string s_logistics { get; set; }
        public string s_logisticsid { get; set; }
        public string s_address { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual product product { get; set; }
        public virtual staff staff { get; set; }
    }
}
