//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public staff()
        {
            this.instorages = new HashSet<instorage>();
            this.outstorages = new HashSet<outstorage>();
            this.pur_indent = new HashSet<pur_indent>();
            this.pur_MRB = new HashSet<pur_MRB>();
            this.pur_quality = new HashSet<pur_quality>();
            this.pur_quotation = new HashSet<pur_quotation>();
            this.pur_quotation1 = new HashSet<pur_quotation>();
            this.sale_indent = new HashSet<sale_indent>();
            this.sale_quotation = new HashSet<sale_quotation>();
        }
    
        public int s_id { get; set; }
        public string s_name { get; set; }
        public string s_sex { get; set; }
        public Nullable<System.DateTime> s_birth { get; set; }
        public string s_nation { get; set; }
        public string s_location { get; set; }
        public string s_address { get; set; }
        public string s_politics { get; set; }
        public string s_education { get; set; }
        public Nullable<int> s_section { get; set; }
        public Nullable<int> s_station { get; set; }
        public string s_tel { get; set; }
        public string s_note { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<instorage> instorages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<outstorage> outstorages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pur_indent> pur_indent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pur_MRB> pur_MRB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pur_quality> pur_quality { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pur_quotation> pur_quotation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pur_quotation> pur_quotation1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sale_indent> sale_indent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sale_quotation> sale_quotation { get; set; }
        public virtual section section { get; set; }
        public virtual station station { get; set; }
    }
}
